// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proposal} from '../models';
import {agent} from '../models';
import {bible} from '../models';
import {main} from '../models';
import {summary} from '../models';
import {project} from '../models';
import {snapshot} from '../models';
import {notion} from '../models';
import {publish} from '../models';
import {settings} from '../models';

export function AcceptProposal(arg1:string,arg2:any):Promise<proposal.Proposal>;

export function ApplyEntityHeader(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function AskAI(arg1:agent.AskParams):Promise<void>;

export function BibleIndex():Promise<bible.Index>;

export function CancelAsk():Promise<void>;

export function ChapterWordCounts():Promise<Record<string, number>>;

export function ClearCover():Promise<void>;

export function CloseProject():Promise<void>;

export function ConvertOptions():Promise<Array<main.Option>>;

export function CopyChapter(arg1:string,arg2:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<main.SettingsView>;

export function DraftSummary(arg1:string):Promise<string>;

export function EntityTypes():Promise<Array<string>>;

export function ExportVolume(arg1:number,arg2:string):Promise<string>;

export function FindVariants():Promise<Array<bible.Variant>>;

export function GetCover():Promise<string>;

export function GetSettings():Promise<main.SettingsView>;

export function GetSummary(arg1:string):Promise<summary.Summary>;

export function GetTree():Promise<project.Tree>;

export function IgnoreVariant(arg1:string):Promise<void>;

export function ListModels(arg1:string):Promise<Array<string>>;

export function ListProposals():Promise<Array<proposal.Proposal>>;

export function ListRecent():Promise<Array<main.RecentView>>;

export function ListSnapshots():Promise<Array<snapshot.Meta>>;

export function NewChapter(arg1:string,arg2:number):Promise<string>;

export function NewDoc(arg1:string,arg2:string,arg3:string):Promise<string>;

export function NotionApply(arg1:string,arg2:Record<string, string>,arg3:Record<string, string>):Promise<notion.Result>;

export function NotionScan(arg1:string):Promise<notion.Plan>;

export function NotionUndo(arg1:string):Promise<Array<string>>;

export function OpenProjectAt(arg1:string):Promise<project.Tree>;

export function ParseEntity(arg1:string,arg2:string):Promise<bible.Entity>;

export function PickAndCreateProject(arg1:string):Promise<project.Tree>;

export function PickAndOpenProject():Promise<project.Tree>;

export function PickCover():Promise<string>;

export function PickNotionExport(arg1:boolean):Promise<string>;

export function PreviewContext(arg1:agent.AskParams):Promise<agent.Preview>;

export function PreviewExport(arg1:string,arg2:publish.Rules):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RejectProposal(arg1:string):Promise<void>;

export function RemoveRecent(arg1:string):Promise<void>;

export function RenameProject(arg1:string):Promise<project.Tree>;

export function ResetChat():Promise<void>;

export function ResetPlatforms():Promise<main.SettingsView>;

export function RestoreSnapshot(arg1:string,arg2:Array<string>):Promise<snapshot.Meta>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SavePlatforms(arg1:Array<publish.Platform>):Promise<main.SettingsView>;

export function SaveProfile(arg1:settings.Profile,arg2:any):Promise<main.SettingsView>;

export function SaveSummary(arg1:string,arg2:string):Promise<summary.Summary>;

export function SetActiveModel(arg1:string,arg2:string):Promise<main.SettingsView>;

export function SetChapterStatus(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetVolumes(arg1:Array<project.Volume>):Promise<project.Tree>;

export function SnapshotDiff(arg1:string,arg2:string):Promise<Array<snapshot.DiffLine>>;

export function SuggestAttachments(arg1:string):Promise<Array<string>>;

export function TakeSnapshot(arg1:string):Promise<snapshot.Meta>;

export function TrashFile(arg1:string):Promise<project.Tree>;

export function WordCount(arg1:string):Promise<number>;
