// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptProposal(arg1, arg2) {
  return window['go']['main']['App']['AcceptProposal'](arg1, arg2);
}

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function ApplyEntityHeader(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyEntityHeader'](arg1, arg2, arg3, arg4);
}

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function BibleIndex() {
  return window['go']['main']['App']['BibleIndex']();
}

export function CancelAsk() {
  return window['go']['main']['App']['CancelAsk']();
}

export function CategoryUsage(arg1) {
  return window['go']['main']['App']['CategoryUsage'](arg1);
}

export function ChapterWordCounts() {
  return window['go']['main']['App']['ChapterWordCounts']();
}

export function ClearCover() {
  return window['go']['main']['App']['ClearCover']();
}

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function ConvertOptions() {
  return window['go']['main']['App']['ConvertOptions']();
}

export function CopyChapter(arg1, arg2) {
  return window['go']['main']['App']['CopyChapter'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DraftSummary(arg1) {
  return window['go']['main']['App']['DraftSummary'](arg1);
}

export function EntityTypes() {
  return window['go']['main']['App']['EntityTypes']();
}

export function ExportVolume(arg1, arg2) {
  return window['go']['main']['App']['ExportVolume'](arg1, arg2);
}

export function FindVariants() {
  return window['go']['main']['App']['FindVariants']();
}

export function GetCover() {
  return window['go']['main']['App']['GetCover']();
}

export function GetResearch() {
  return window['go']['main']['App']['GetResearch']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function GetTree() {
  return window['go']['main']['App']['GetTree']();
}

export function IgnoreVariant(arg1) {
  return window['go']['main']['App']['IgnoreVariant'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListProposals() {
  return window['go']['main']['App']['ListProposals']();
}

export function ListRecent() {
  return window['go']['main']['App']['ListRecent']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function NewChapter(arg1, arg2) {
  return window['go']['main']['App']['NewChapter'](arg1, arg2);
}

export function NewDoc(arg1, arg2, arg3) {
  return window['go']['main']['App']['NewDoc'](arg1, arg2, arg3);
}

export function NotionApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotionApply'](arg1, arg2, arg3);
}

export function NotionScan(arg1) {
  return window['go']['main']['App']['NotionScan'](arg1);
}

export function NotionUndo(arg1) {
  return window['go']['main']['App']['NotionUndo'](arg1);
}

export function OpenProjectAt(arg1) {
  return window['go']['main']['App']['OpenProjectAt'](arg1);
}

export function ParseEntity(arg1, arg2) {
  return window['go']['main']['App']['ParseEntity'](arg1, arg2);
}

export function PickAndCreateProject(arg1) {
  return window['go']['main']['App']['PickAndCreateProject'](arg1);
}

export function PickAndOpenProject() {
  return window['go']['main']['App']['PickAndOpenProject']();
}

export function PickCover() {
  return window['go']['main']['App']['PickCover']();
}

export function PickNotionExport(arg1) {
  return window['go']['main']['App']['PickNotionExport'](arg1);
}

export function PreviewContext(arg1) {
  return window['go']['main']['App']['PreviewContext'](arg1);
}

export function PreviewExport(arg1, arg2) {
  return window['go']['main']['App']['PreviewExport'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RejectProposal(arg1) {
  return window['go']['main']['App']['RejectProposal'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['main']['App']['RemoveRecent'](arg1);
}

export function RenameProject(arg1) {
  return window['go']['main']['App']['RenameProject'](arg1);
}

export function ResearchOpenFile(arg1) {
  return window['go']['main']['App']['ResearchOpenFile'](arg1);
}

export function ResetChat() {
  return window['go']['main']['App']['ResetChat']();
}

export function ResetPlatforms() {
  return window['go']['main']['App']['ResetPlatforms']();
}

export function RestoreSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SavePlatforms(arg1) {
  return window['go']['main']['App']['SavePlatforms'](arg1);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SaveSummary(arg1, arg2) {
  return window['go']['main']['App']['SaveSummary'](arg1, arg2);
}

export function SetActiveModel(arg1, arg2) {
  return window['go']['main']['App']['SetActiveModel'](arg1, arg2);
}

export function SetChapterStatus(arg1, arg2) {
  return window['go']['main']['App']['SetChapterStatus'](arg1, arg2);
}

export function SetResearch(arg1) {
  return window['go']['main']['App']['SetResearch'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetVolumes(arg1) {
  return window['go']['main']['App']['SetVolumes'](arg1);
}

export function SnapshotDiff(arg1, arg2) {
  return window['go']['main']['App']['SnapshotDiff'](arg1, arg2);
}

export function SuggestAttachments(arg1) {
  return window['go']['main']['App']['SuggestAttachments'](arg1);
}

export function TakeSnapshot(arg1) {
  return window['go']['main']['App']['TakeSnapshot'](arg1);
}

export function TrashFile(arg1) {
  return window['go']['main']['App']['TrashFile'](arg1);
}

export function WordCount(arg1) {
  return window['go']['main']['App']['WordCount'](arg1);
}
